# platform :ios, '9.0'


target 'LegalAWy' do
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',

        # Add any other subspecs you want to use in your project
      ]

      pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
      pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
      # If you are using React Native <0.54, you will get the following error:
      # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
      # Use the following line instead:
      #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
      pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
      pod 'react-native-maps', path: rn_maps_path
      pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
      pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
      pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS    
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end